version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./src:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    volumes:
      - ./src:/var/www/html